Repository raphaelvallat/pingouin, pull requests merged in 2022-06, with the labels that each got.

#254 Fix eta-squared calculation in repeated measures ANOVA design
  README.rst
  docs/changelog.rst
  docs/index.rst
  notebooks/00_QuickStart.ipynb
  notebooks/01_ANOVA.ipynb
  pingouin/parametric.py
  pingouin/power.py
  pingouin/tests/test_parametric.py
Labels: invalid :triangular_flag_on_post:, IMPORTANT❗

#278 Use scikit-learn<1.1.0
  docs/changelog.rst
  requirements.txt
  setup.py
Labels: bug :boom:

#280 Renamed eta to eta-squared in power functions
  docs/changelog.rst
  notebooks/01_ANOVA.ipynb
  pingouin/power.py
  pingouin/tests/test_power.py
Labels: docs/testing:book:

#281 [bugfix] resample x and y separately in bootci when paired=False
  docs/changelog.rst
  notebooks/03_EffectSizes.ipynb
  pingouin/effsize.py
  pingouin/tests/test_effsize.py
Labels: bug :boom:

#282 Fix ci in plot_shift + doc improvements in bootstrap
  docs/changelog.rst
  pingouin/bayesian.py
  pingouin/effsize.py
  pingouin/pairwise.py
  pingouin/plotting.py
  pingouin/regression.py
  pingouin/tests/test_plotting.py
Labels: bug :boom:

#283 Black formatting
  .github/workflows/black.yml
  docs/changelog.rst
  docs/conf.py
  pingouin/__init__.py
  pingouin/bayesian.py
  pingouin/circular.py
  pingouin/config.py
  pingouin/contingency.py
  pingouin/correlation.py
  pingouin/datasets/__init__.py
  pingouin/distribution.py
  pingouin/effsize.py
  pingouin/equivalence.py
  pingouin/multicomp.py
  pingouin/multivariate.py
  pingouin/nonparametric.py
  pingouin/pairwise.py
  pingouin/parametric.py
  pingouin/plotting.py
  pingouin/power.py
  pingouin/regression.py
  pingouin/reliability.py
  pingouin/tests/test_bayesian.py
  pingouin/tests/test_circular.py
  pingouin/tests/test_contingency.py
  pingouin/tests/test_correlation.py
  pingouin/tests/test_distribution.py
  pingouin/tests/test_effsize.py
  pingouin/tests/test_equivalence.py
  pingouin/tests/test_multicomp.py
  pingouin/tests/test_multivariate.py
  pingouin/tests/test_nonparametric.py
  pingouin/tests/test_pairwise.py
  pingouin/tests/test_pandas.py
  pingouin/tests/test_parametric.py
  pingouin/tests/test_plotting.py
  pingouin/tests/test_power.py
  pingouin/tests/test_regression.py
  pingouin/tests/test_reliability.py
  pingouin/tests/test_utils.py
  pingouin/utils.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: docs/testing:book:

#286 Add support for DataMatrix objects
  pingouin/nonparametric.py
  pingouin/pairwise.py
  pingouin/parametric.py
  pingouin/plotting.py
  pingouin/utils.py
Labels: feature request :construction:
