Repository raphaelvallat/pingouin, pull requests merged in 2022-02, with the labels that each got.

#229 ENH: use studentized range over statsmodels for pairwise tests
  docs/changelog.rst
  pingouin/pairwise.py
Labels: feature request :construction:

#234 Fixes for dependency (scipy and pandas) updates
  pingouin/correlation.py
  pingouin/pairwise.py
  pingouin/parametric.py
  pingouin/plotting.py
Labels: bug :boom:

#236 Release v0.5.1
  README.rst
  docs/changelog.rst
  docs/index.rst
  pingouin/__init__.py
  pingouin/distribution.py
  pingouin/pairwise.py
  pingouin/parametric.py
  pingouin/regression.py
  pingouin/tests/test_correlation.py
  pingouin/tests/test_distribution.py
  pingouin/tests/test_pairwise.py
  pingouin/tests/test_parametric.py
  pingouin/tests/test_utils.py
  pingouin/utils.py
  requirements.txt
  setup.py
Labels: IMPORTANT❗
